spring.application.name=TwoMicroservices
server.port=9090

# DB properties
spring.datasource.url=jdbc:postgresql://localhost:7203/TwoMicroservices
spring.datasource.username=postgres
spring.datasource.password=Kb%8zh_1q
spring.datasource.driver-class-name=org.postgresql.Driver

# JWT properties
jwt.signingKey=364387F6801388923FA3D34F52190A5597911ACC4983A66D511164EA2E60F02F
jwt.ExpirationTime=8640000

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true